Feature/victorowsky/cart screen
dr0er/ecommerce-gaming-shop pull request #11
Opened 2021-09-02 12:15 UTC by Victorowsky

2021-09-07 18:57 UTC, stepaniukm requested changes
In general very decent code. 

Please read more about [headers structure](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) and you should also read about `pure functions`, then try to find functions that could be converted to pure in your code.

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/CartItem.tsx
> +const CartItem = ({ data }: CartItemProps) => {
I think this nesting is not needed, you could simply pass props like `id`, `image` etc. instead of `data.id`, `data.image`...

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/CartItem.tsx
> +				<h2 className="font-extrabold text-xl mt-auto">{price}€</h2>
Price in `h2`? This is not correct use of header. They have semantic meaning.

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/CartScreen.tsx
> +			{/* Item list */}
What't the point of this comment?

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/CartScreen.tsx
> +			<h1 className="text-3xl font-extrabold py-5">My cart</h1>
`h1` should be one on a page and definitely cart is not that important to be given this privilege.

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/CartScreenSlice.ts
> +interface productProps {
Types should start with a capital letter. 
```suggestion
interface ProductProps {
```

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/CartScreenSlice.ts
> +	myProducts: [] as productProps[],
I get your idea, but you 're approaching the problem from the wrong side. Instead of type casting using `as` you should create type for your entire state. Please note that `createSlice` is generic and can take type of state as an "argument".

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/CartScreenSlice.ts
> +		addProduct: (state, action) => {
Why `addProduct` doesn't cover the case when the product is not yet in cart?

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/CartScreenSlice.ts
> +		removeProduct: (state, action) => {
and what if there's one product in cart?

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/Summary.tsx
> +interface productProps {
Please note that you keep repeating this type or very similar many times throughout the project.

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/Summary.tsx
> +		let price = 0;
You could do this cleaner using `reduce` method. It's worth to know.

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/Summary.tsx
> +		const shippingPrice = 5;
This const should not be kept here inside the function, it should be more global.

2021-09-07 18:57 UTC, stepaniukm commented on Frontend/src/Components/CartScreen/Summary.tsx
> +		let price = handleSubtotal();
Why using `let`? You can simply `return price + shippingPrice`

2021-09-19 18:18 UTC, nezouse commented
Can you run prettier in all committed files before merging? Formatting is wrong in several places.

2021-09-20 16:33 UTC, nezouse commented on Frontend/src/Components/CartScreen/Summary.tsx
> +		let price = 0;
const totalPrice = myProducts.reduce(
  (accumulator, product) => (accumulator += product.price * product.amount),
  0 // 0 is a initial value for accumulator
);

2021-09-20 16:34 UTC, nezouse commented on Frontend/src/Components/CartScreen/Summary.tsx
> +		return (price += shippingPrice);
No need to use `+=` here. `price + shippingPrice` will do the same

2021-09-20 20:02 UTC, stepaniukm commented
Please resolve conflicts

2021-09-22 13:13 UTC, nezouse approved these changes

2021-09-22 13:13 UTC, nezouse commented on Frontend/src/Components/CartScreen/CartScreen.tsx
> +  ))
This would be better extracted as separate component

2021-09-22 13:41 UTC, nezouse commented on Frontend/src/Components/CartScreen/CartScreenSlice.ts
> +export interface ProductProps {
It should be named just `Product` because it's a model and not properties (props)

2021-09-22 13:41 UTC, nezouse commented on Frontend/src/Components/CartScreen/CartScreen.tsx
> +  }
Should use Array<Product> from redux slice

2021-09-23 18:30 UTC, merged