added Log in and Sign up buttons and LandingPage styles changed from …
dr0er/ecommerce-gaming-shop pull request #17
Opened 2021-09-12 09:35 UTC by tomaszciula

…css to tailwind

2021-09-12 09:44 UTC, stepaniukm requested changes

2021-09-12 09:44 UTC, stepaniukm commented on Frontend/src/Components/landingPage/LandingPage.tsx
> +    //<div className="landingPage_Container">
Why you add those comments?

2021-09-12 09:44 UTC, stepaniukm commented on Frontend/tailwind.config.js
> +        'straganLandingPageBackground': "url('./Assets/background-lp.jpg')",
We shouldn't bind important things like appName to styles like this. What if conception changes and our app will no longer be named `stragan`? Changing all of the styles only because of that? In styles we should be more general in naming and use names like `primary` etc.

2021-09-12 09:44 UTC, stepaniukm commented on Frontend/tailwind.config.js
> +      backgroundImage: theme => ({
You don't use `theme` so you can use normal object syntax instead of function here.

2021-09-15 19:31 UTC, stepaniukm commented on Frontend/tailwind.config.js
> +        'LandingPageBackground': "url('./Assets/background-lp.jpg')"
convention is to use `kebab-case` and not `PascalCase`

2021-09-15 19:31 UTC, stepaniukm approved these changes

2021-09-16 20:26 UTC, dee2ess commented
Please, resolve the confilcts on your branch.

2021-09-18 19:43 UTC, merged