Feature/pawelpikus/registerpage
dr0er/ecommerce-gaming-shop pull request #26
Opened 2021-09-14 19:15 UTC by pawelpikus

Please have a look at the code for registering a user

2021-09-14 22:18 UTC, mkokosinski requested changes

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +export default function RegisterForm() {
zmień na arrow, do obsługi formów przydałby się jakiś elastyczny komponent lub hook, kiedyś była mowa o react hooks form, możesz dopytać na to na kanale frontend

brak walidacji i obsługi errorów

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +    password2: '',
passwordConfirmation lub coś w ten deseń to bardziej adekwatna nazwa

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +  function handleChange(e: any): void {
arrow func, niżej nie będę się już z tym powtarzał
podobnie jak z any, unikaj takich typów jak any, object etc, używaj konkretnych typów jak np ChangeEvent<HTMLInputElement>

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +        })
Do logiki nie będę się niżej rozpisywał bo na pewno formy inaczej obsłużymy, ale zawsze warto pisać kod w miarę czytelnie np.

```suggestion
  setUserData({
          ...userData,
          [name]: type === 'checkbox' ? checked : value,
        })
```

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +  }
mógłbyś to wrzucić  w 1 stan i obsłużyć podobnie jak inputy w zależności od name

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +                        }  border-grey-light focus:opacity-100 bg-background-grey`}
do conditionali w className lepiej użyć tak jak koledzy np libki clsx. Dużo czytelniej to wypada

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +          <input
w inpucie brak attr id, jak korzystasz z label i for, to fajnie już żeby przeglądarka po kliknięciu w label dała focus na konkretny input

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +        </div>
Input również zasługuje na swój uniwersalny komponent. Ogólnie staraj się nie powtarzać w kodzie, który piszesz tylko wyodrębniaj te kawałki kodu do funkcji i komponentów

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +        </div>
Masz position absolute wewnąrz inputa, wpisz bardzo długie hasło i zobacz co się wydarzy

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +              className={`py-2 px-6 w-full  rounded-2xl outline-none border-2
po co w tych inputach tutaj template string?

2021-09-14 22:18 UTC, mkokosinski commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +          </div>
osobny komponent

2021-09-15 07:00 UTC, pawelpikus commented on Frontend/package.json
> +    "daisyui": "^1.14.0",
Użyłem do checkboxa, masz rację poprawię na swój

2021-09-15 07:00 UTC, pawelpikus commented on Frontend/src/Components/landingPage/LandingPage.tsx
> +        <Link to="/signup">
ok

2021-09-15 07:02 UTC, pawelpikus commented on Frontend/src/Components/registerPage/RegisterBtn.tsx
> +export default function RegisterBtn(props: { btnText: string; register: any }) {
słusznie, dzięki

2021-09-15 07:03 UTC, pawelpikus commented on Frontend/src/Components/registerPage/RegisterBtn.tsx
> +        onClick={() => props.register}>
Dzięki, spróbuję to poprawić

2021-09-18 15:20 UTC, nezouse commented on Frontend/package.json
> +    "react-hook-form": "^7.15.3",
You are not using it anywhere in the PR

2021-09-19 18:21 UTC, nezouse commented
Hi, could you run npm install with npm at version 6? Version 7 produces different lockfile.

2021-09-20 19:29 UTC, pawelpikus commented
> Hi, could you run npm install with npm at version 6? Version 7 produces different lockfile.

Hello, alright!

2021-09-20 19:56 UTC, pawelpikus commented
> > Hi, could you run npm install with npm at version 6? Version 7 produces different lockfile.
> 
> Hello, alright!

Should I downgrade Node as well? After downgrading npm I have ERR...

2021-09-20 20:02 UTC, stepaniukm commented
Please resolve conflicts

2021-09-20 20:09 UTC, nezouse commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +  }
It's better to keep types outside of components.

2021-09-20 20:09 UTC, nezouse commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +                        ${!watch('name') && 'opacity-30'}
Using watch in general is not a good idea until you really have to.  What is the reason for it to have reduced opacity?

2021-09-20 20:09 UTC, nezouse commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +          <p className="text-red-500">{errors?.name?.message}</p>
This `p` shouldn't be rendered until there is an actual error. You could probably use this helper component https://react-hook-form.com/api/useformstate/errormessage

2021-09-20 20:09 UTC, nezouse commented on Frontend/src/Components/registerPage/RegisterForm.tsx
> +            focus-within:opacity-100 `}>
Conditional styles should be applied with `clsx` library

2021-09-23 18:29 UTC, closed without merging

2021-09-23 18:29 UTC, dr0er commented
Already merged to dev