Feature/dr0er/create navbar
dr0er/ecommerce-gaming-shop pull request #28
Opened 2021-09-16 10:41 UTC by dr0er

2021-09-16 10:58 UTC, stepaniukm requested changes
Redux here is not needed, we should make this state local.

2021-09-16 18:32 UTC, stepaniukm commented on Frontend/src/Components/Navbar/Menu.tsx
> +	const handleCloseMenu = () => {
Unnecessary, you can simply use `onClose` in JSX

2021-09-16 18:33 UTC, stepaniukm commented on Frontend/src/Components/Navbar/MenuItem.tsx
> +    children: string;
This type is not correct, children is `React.ReactNode`

2021-09-16 18:34 UTC, stepaniukm commented on Frontend/src/Components/Navbar/Navbar.tsx
> +	const handleOpenMenu = () => {
When passing function as a prop a good practice is to wrap it into `useCallback` to avoid unnecessary rerenders.

2021-09-16 18:34 UTC, stepaniukm commented on Frontend/src/Store/store.ts
> +	reducer: {},
Not needed anymore

2021-09-17 13:28 UTC, dr0er commented on Frontend/src/Store/store.ts
> +	reducer: {},
We agreed not to delete anything here

2021-09-17 13:29 UTC, dr0er commented on Frontend/src/Components/Navbar/Navbar.tsx
> +	const handleOpenMenu = () => {
Fixed

2021-09-17 13:29 UTC, dr0er commented on Frontend/src/Components/Navbar/MenuItem.tsx
> +    children: string;
Changed

2021-09-21 16:50 UTC, nezouse approved these changes

2021-09-21 16:52 UTC, merged